import type { Metadata } from 'next';
import { Poppins } from '@/public/fonts';
import '../styles/globals.css';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body className={`${Poppins.variable} antialiased`}>
				<div className='px-5'>{children} </div>
			</body>
		</html>
	);
}
